/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * crossZero.java
 *
 * Created on Mar 16, 2012, 10:59:28 AM
 */


import javax.swing.JButton;

/**
 * 
 * @author harshal
 */
public class crossZero extends javax.swing.JFrame {

	static int STATE_ZERO = 0;
	static int HORIZONTAL_STATE = -1;
	static int VERTICAL_STATE = -1;
	static int CROSS_STATE = -1;
	static String winning_player;
	static int WIN_STATE = -1;
	static int TURN = 0;
	static int GAME_OVER = 0;
	String buttonString;
	static int cross_Score = 0;
	static int zero_Score = 0;

	/** Creates new form crossZero */
	public crossZero() {
		initComponents();
		// buttonString = b1.getText() + b2.getText() + b3.getText() +
		// b4.getText() + b5.getText() + b6.getText() + b7.getText() +
		// b8.getText() + b9.getText();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	public void setStatus(JButton b) {
		if (STATE_ZERO == 0) {
			b.setText("O");
			statusLabel.setText("NOW IT'S Player-XXX TURN");
			b.setEnabled(false);
			STATE_ZERO = 1;
		} else if (STATE_ZERO == 1) {
			b.setText("X");
			statusLabel.setText("NOW IT'S Player-OOO TURN");
			b.setEnabled(false);
			STATE_ZERO = 0;
		}

	}

	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel2 = new javax.swing.JPanel();
		jPanel3 = new javax.swing.JPanel();
		b1 = new javax.swing.JButton();
		b2 = new javax.swing.JButton();
		b3 = new javax.swing.JButton();
		b4 = new javax.swing.JButton();
		b5 = new javax.swing.JButton();
		b6 = new javax.swing.JButton();
		b7 = new javax.swing.JButton();
		b8 = new javax.swing.JButton();
		b9 = new javax.swing.JButton();
		resetButton = new javax.swing.JButton();
		statusLabel = new javax.swing.JLabel();
		scorePanel = new javax.swing.JPanel();
		ScoreLabel = new javax.swing.JLabel();
		zeroLabel = new javax.swing.JLabel();
		crossLabel = new javax.swing.JLabel();
		zeroScoreLabel = new javax.swing.JLabel();
		crossScoreLabel = new javax.swing.JLabel();

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 100,
				Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 100,
				Short.MAX_VALUE));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 100,
				Short.MAX_VALUE));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 100,
				Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("CROSS ZERO GAME");
		setBackground(new java.awt.Color(102, 102, 102));
		setFont(new java.awt.Font("Adobe Caslon Pro Bold", 1, 24));
		setForeground(new java.awt.Color(255, 51, 0));
		setLocationByPlatform(true);
		setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
		setResizable(false);

		b1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 48));
		b1.setForeground(new java.awt.Color(0, 0, 102));
		b1.setText(".");
		b1.setToolTipText("click to take turn");
		b1.setBorder(null);
		b1.setRequestFocusEnabled(false);
		b1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				b1ActionPerformed(evt);
			}
		});

		b2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 48)); // NOI18N
		b2.setForeground(new java.awt.Color(0, 0, 102));
		b2.setText(".");
		b2.setToolTipText("click to take turn");
		b2.setBorder(null);
		b2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				b2ActionPerformed(evt);
			}
		});

		b3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 48)); // NOI18N
		b3.setForeground(new java.awt.Color(0, 0, 102));
		b3.setText(".");
		b3.setToolTipText("click to take turn");
		b3.setBorder(null);
		b3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				b3ActionPerformed(evt);
			}
		});

		b4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 48));
		b4.setForeground(new java.awt.Color(0, 0, 102));
		b4.setText(".");
		b4.setToolTipText("click to take turn");
		b4.setBorder(null);
		b4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				b4ActionPerformed(evt);
			}
		});

		b5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 48));
		b5.setForeground(new java.awt.Color(0, 0, 102));
		b5.setText(".");
		b5.setToolTipText("click to take turn");
		b5.setBorder(null);
		b5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				b5ActionPerformed(evt);
			}
		});

		b6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 48));
		b6.setForeground(new java.awt.Color(0, 0, 102));
		b6.setText(".");
		b6.setToolTipText("click to take turn");
		b6.setBorder(null);
		b6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				b6ActionPerformed(evt);
			}
		});

		b7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 48));
		b7.setForeground(new java.awt.Color(0, 0, 102));
		b7.setText(".");
		b7.setToolTipText("click to take turn");
		b7.setBorder(null);
		b7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				b7ActionPerformed(evt);
			}
		});

		b8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 48));
		b8.setForeground(new java.awt.Color(0, 0, 102));
		b8.setText(".");
		b8.setToolTipText("click to take turn");
		b8.setBorder(null);
		b8.setFocusPainted(false);
		b8.setHideActionText(true);
		b8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				b8ActionPerformed(evt);
			}
		});

		b9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 3, 48));
		b9.setForeground(new java.awt.Color(0, 0, 102));
		b9.setText(".");
		b9.setToolTipText("click to take turn"); // NOI18N
		b9.setBorder(null);
		b9.setFocusPainted(false);
		b9.setHideActionText(true);
		b9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				b9ActionPerformed(evt);
			}
		});

		resetButton.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold",
				0, 36));
		resetButton.setForeground(new java.awt.Color(255, 0, 0));
		resetButton.setText("Reset");
		resetButton.setToolTipText("Click to start new game");
		resetButton.setCursor(new java.awt.Cursor(
				java.awt.Cursor.DEFAULT_CURSOR));
		resetButton
				.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
		resetButton.setFocusCycleRoot(true);
		resetButton.setHideActionText(true);
		resetButton.setRolloverEnabled(false);
		resetButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				resetButtonActionPerformed(evt);
			}
		});

		statusLabel.setBackground(new java.awt.Color(0, 0, 0));
		statusLabel.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
		statusLabel.setForeground(new java.awt.Color(0, 0, 102));
		statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		statusLabel.setText("   Ready  for  Playing....");
		statusLabel.setBorder(new javax.swing.border.LineBorder(
				new java.awt.Color(0, 0, 0), 1, true));
		statusLabel.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
		statusLabel.setName(""); // NOI18N

		scorePanel.setBackground(new java.awt.Color(0, 0, 0));

		ScoreLabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold",
				1, 24)); // NOI18N
		ScoreLabel.setForeground(java.awt.Color.red);
		ScoreLabel.setText("<User Code>");
		new displaytransition("Score-Board  ", ScoreLabel);

		zeroLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
		zeroLabel.setForeground(new java.awt.Color(255, 0, 0));
		zeroLabel.setText("Player Zero");

		crossLabel.setFont(new java.awt.Font("Times New Roman", 1, 14));
		crossLabel.setForeground(java.awt.Color.red);
		crossLabel.setText("Player Cross");

		zeroScoreLabel.setFont(new java.awt.Font("Times New Roman", 1, 24));
		zeroScoreLabel.setForeground(new java.awt.Color(255, 0, 0));
		zeroScoreLabel
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		zeroScoreLabel.setText("0");

		crossScoreLabel.setFont(new java.awt.Font("Times New Roman", 1, 24));
		crossScoreLabel.setForeground(new java.awt.Color(255, 0, 0));
		crossScoreLabel
				.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		crossScoreLabel.setText("0");

		javax.swing.GroupLayout scorePanelLayout = new javax.swing.GroupLayout(
				scorePanel);
		scorePanel.setLayout(scorePanelLayout);
		scorePanelLayout
				.setHorizontalGroup(scorePanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								scorePanelLayout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												scorePanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																scorePanelLayout
																		.createSequentialGroup()
																		.addGroup(
																				scorePanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								zeroLabel)
																						.addGroup(
																								scorePanelLayout
																										.createSequentialGroup()
																										.addGap(10,
																												10,
																												10)
																										.addComponent(
																												zeroScoreLabel,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												44,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				37,
																				Short.MAX_VALUE)
																		.addGroup(
																				scorePanelLayout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								scorePanelLayout
																										.createSequentialGroup()
																										.addGap(10,
																												10,
																												10)
																										.addComponent(
																												crossScoreLabel,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												44,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addComponent(
																								crossLabel))
																		.addContainerGap())
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																scorePanelLayout
																		.createSequentialGroup()
																		.addComponent(
																				ScoreLabel)
																		.addGap(36,
																				36,
																				36)))));
		scorePanelLayout
				.setVerticalGroup(scorePanelLayout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								scorePanelLayout
										.createSequentialGroup()
										.addComponent(ScoreLabel)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												scorePanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																zeroLabel,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																24,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																crossLabel))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												scorePanelLayout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																crossScoreLabel,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																zeroScoreLabel,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap(14, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		b4,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		b5,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		b6,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		b1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		b2,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		b3,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		b7,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		b8,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addComponent(
																		b9,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		50,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(47, 47, 47)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														scorePanel,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(
														resetButton,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														146,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap())
				.addComponent(statusLabel,
						javax.swing.GroupLayout.Alignment.TRAILING,
						javax.swing.GroupLayout.DEFAULT_SIZE, 433,
						Short.MAX_VALUE));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						b1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						50,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						b2,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						50,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						b3,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						50,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						b4,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						50,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						b5,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						50,
																						javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(
																						b6,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						50,
																						javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				false)
																				.addComponent(
																						b7,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						50,
																						Short.MAX_VALUE)
																				.addComponent(
																						b8,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						50,
																						Short.MAX_VALUE)
																				.addComponent(
																						b9,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						50,
																						Short.MAX_VALUE)))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		scorePanel,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18,
																		18)
																.addComponent(
																		resetButton,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		55,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(18, 18, 18)
								.addComponent(statusLabel,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										41, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	public void method(JButton b) {
		TURN++;

		setStatus(b);// set label status
		buttonString = b1.getText() + b2.getText() + b3.getText()
				+ b4.getText() + b5.getText() + b6.getText() + b7.getText()
				+ b8.getText() + b9.getText();
		System.out.println(buttonString + "\n\n\n");
		statusCheck(buttonString);
		if (GAME_OVER == 1) {
			b1.setEnabled(false);
			b2.setEnabled(false);
			b3.setEnabled(false);
			b4.setEnabled(false);
			b5.setEnabled(false);
			b6.setEnabled(false);
			b7.setEnabled(false);
			b8.setEnabled(false);
			b9.setEnabled(false);
		}
	}

	private void b4ActionPerformed(java.awt.event.ActionEvent evt) {
		method(b4);
	}

	private void b1ActionPerformed(java.awt.event.ActionEvent evt) {

		method(b1);
	}

	private void b2ActionPerformed(java.awt.event.ActionEvent evt) {
		method(b2);
	}

	private void b3ActionPerformed(java.awt.event.ActionEvent evt) {
		method(b3); // TODO add your handling code here:
	}

	private void b5ActionPerformed(java.awt.event.ActionEvent evt) {
		method(b5); // TODO add your handling code here:
	}

	private void b6ActionPerformed(java.awt.event.ActionEvent evt) {
		method(b6); // TODO add your handling code here:
	}

	private void b7ActionPerformed(java.awt.event.ActionEvent evt) {
		method(b7); // TODO add your handling code here:
	}

	private void b8ActionPerformed(java.awt.event.ActionEvent evt) {
		method(b8); // TODO add your handling code here:
	}

	private void b9ActionPerformed(java.awt.event.ActionEvent evt) {
		method(b9); // TODO add your handling code here:
	}

	public void statusCheck(String s) {
		HORIZONTAL_STATE = Methods.setHorizontal(s, HORIZONTAL_STATE);
		VERTICAL_STATE = Methods.setVertical(s, VERTICAL_STATE);
		CROSS_STATE = Methods.setCross(s, CROSS_STATE);
		System.out.println(HORIZONTAL_STATE);
		if (HORIZONTAL_STATE == 1) {
			GAME_OVER = 1;
			System.out.println("Horizontal..PLAYER WIN....");
			if (winning_player.equalsIgnoreCase("XXX")) {
				statusLabel.setText("Player  Cross  Has  Won This Game");
				cross_Score++;
			} else {
				statusLabel.setText("Player  Zero  Has  Won This Game");
				zero_Score++;
			}

		} else if (VERTICAL_STATE == 1) {
			GAME_OVER = 1;
			System.out.println("Vertical PLAYER WIN....");
			if (winning_player.equalsIgnoreCase("XXX")) {
				statusLabel.setText("Player  Cross  Has  Won This Game");
				cross_Score++;
			} else {
				statusLabel.setText("Player  Zero  Has  Won This Game");
				zero_Score++;
			}

		} else if (CROSS_STATE == 1) {
			GAME_OVER = 1;
			System.out.println("Cross PLAYER WIN....");
			if (winning_player.equalsIgnoreCase("XXX")) {
				statusLabel.setText("Player  Cross  Has  Won This Game");
				cross_Score++;
			} else {
				statusLabel.setText("Player  Zero  Has  Won This Game");
				zero_Score++;
			}

		} else if (TURN == 9) {
			statusLabel.setText("                 Game Draw   ");

		}
		zeroScoreLabel.setText(String.valueOf(zero_Score));
		crossScoreLabel.setText(String.valueOf(cross_Score));
	}

	private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {

		setReset();
	}

	public void setReset() {
		STATE_ZERO = 0;
		HORIZONTAL_STATE = -1;
		VERTICAL_STATE = -1;
		CROSS_STATE = -1;
		TURN = 0;
		GAME_OVER = 0;
		statusLabel.setEnabled(true);
		b1.setEnabled(true);
		b2.setEnabled(true);
		b3.setEnabled(true);
		b4.setEnabled(true);
		b5.setEnabled(true);
		b6.setEnabled(true);
		b7.setEnabled(true);
		b8.setEnabled(true);
		b9.setEnabled(true);

		b1.setText(".");
		b2.setText(".");
		b3.setText(".");
		b4.setText(".");
		b5.setText(".");
		b6.setText(".");
		b7.setText(".");
		b8.setText(".");
		b9.setText(".");
		statusLabel.setText("Ready   Players   for   Playing?");

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(crossZero.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(crossZero.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(crossZero.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(crossZero.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);

		}
		// </editor-foltttd>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new crossZero().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JLabel ScoreLabel;
	private javax.swing.JButton b1;
	private javax.swing.JButton b2;
	private javax.swing.JButton b3;
	private javax.swing.JButton b4;
	private javax.swing.JButton b5;
	private javax.swing.JButton b6;
	private javax.swing.JButton b7;
	private javax.swing.JButton b8;
	private javax.swing.JButton b9;
	private javax.swing.JLabel crossLabel;
	private javax.swing.JLabel crossScoreLabel;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JButton resetButton;
	private javax.swing.JPanel scorePanel;
	private javax.swing.JLabel statusLabel;
	private javax.swing.JLabel zeroLabel;
	private javax.swing.JLabel zeroScoreLabel;
	// End of variables declaration

}
